export const REGISTERED = "REGISTERED";
export const NOT_REGISTERED = "NOT_REGISTERED";

export const AUTHENTICATED = "AUTHENTICATED";
export const NOT_AUTHENTICATED = "NOT_AUTHENTICATED";

export const LOGOUT = "LOGOUT";
